"""Local table contracts for the nlpdata workspace."""

from __future__ import annotations

TABLE_CONTRACTS: dict[str, tuple[str, ...]] = {
    "nlp_runs": (
        "run_id",
        "run_scope",
        "source_catalog",
        "started_at",
        "completed_at",
        "status",
        "input_interaction_count",
        "output_row_counts",
        "quality_metrics",
        "publish_diagnostics",
    ),
    "message_mentions": (
        "mention_id",
        "run_id",
        "message_id",
        "source_interaction_id",
        "span_text",
        "label",
        "start_char",
        "end_char",
        "source_type",
        "confidence",
    ),
    "message_person_links": (
        "link_id",
        "run_id",
        "message_id",
        "person_id",
        "person_name",
        "role",
        "link_origin",
        "confidence",
        "evidence_type",
        "evidence_value",
        "source_interaction_id",
        "is_current",
    ),
    "candidate_assertions": (
        "candidate_assertion_id",
        "run_id",
        "assertion_type",
        "subject_canonical_id",
        "proposed_claim",
        "evidence_refs",
        "provenance_summary",
        "confidence_level",
        "generation_scope",
        "generated_at",
        "review_class",
        "promotion_class",
    ),
    "candidate_assertions_summary": (
        "run_id",
        "generation_scope",
        "emitted_candidate_count",
        "candidate_counts_by_type",
        "suppressed_counts",
        "example_candidate_ids",
        "generated_at",
        "reviewed_effect_counts",
    ),
    "reviewed_effects": (
        "run_id",
        "candidate_assertion_id",
        "assertion_type",
        "subject_canonical_id",
        "result",
        "reason_code",
        "details",
    ),
    "person_person_edges": (
        "pair_id",
        "person_a_id",
        "person_b_id",
        "run_id",
        "generation_scope",
        "strength_score",
        "relationship_signal",
        "direct_evidence_count",
        "indirect_evidence_count",
        "strongest_evidence_ref",
        "is_current",
    ),
    "person_person_edge_evidence": (
        "pair_evidence_id",
        "pair_id",
        "evidence_family",
        "source_ref",
        "contribution_score",
        "rank_within_pair",
        "message_ref",
        "theme_refs",
        "provenance",
    ),
    "phases": (
        "phase_id",
        "run_id",
        "generation_scope",
        "phase_index",
        "start_at",
        "end_at",
        "interaction_count",
        "representative_interaction_ref",
        "boundary_reason",
        "is_current",
    ),
    "phase_central_people": (
        "phase_id",
        "run_id",
        "person_id",
        "rank",
        "centrality_score",
        "interaction_count",
        "evidence_ref",
        "is_current",
    ),
    "phase_theme_summaries": (
        "phase_id",
        "run_id",
        "theme",
        "rank",
        "theme_score",
        "message_count",
        "evidence_ref",
        "is_current",
    ),
    "phase_pair_summaries": (
        "phase_pair_id",
        "phase_id",
        "pair_id",
        "run_id",
        "pair_rank",
        "activity_score",
        "relationship_signal",
        "evidence_count",
        "strongest_evidence_ref",
        "is_current",
    ),
    "phase_pair_evidence": (
        "phase_pair_evidence_id",
        "phase_pair_id",
        "phase_id",
        "pair_id",
        "source_ref",
        "message_ref",
        "evidence_family",
        "rank_within_phase_pair",
        "contribution_score",
        "is_current",
    ),
    "phase_representative_interactions": (
        "phase_id",
        "run_id",
        "interaction_ref",
        "rank",
        "selection_reason",
        "is_current",
    ),
    "phase_diagnostics": (
        "run_id",
        "phase_id",
        "diagnostic_type",
        "result",
        "reason_code",
        "sample_ref",
        "details",
    ),
    "message_theme_tags": (
        "theme_tag_id",
        "run_id",
        "message_id",
        "theme",
        "confidence",
        "evidence",
        "source_method",
        "source_interaction_id",
        "is_current",
    ),
    "message_search_docs": (
        "message_id",
        "run_id",
        "source_interaction_id",
        "source_type",
        "timestamp",
        "subject_terms",
        "body_terms",
        "linked_person_ids",
        "linked_person_names",
        "explicit_person_ids",
        "inferred_person_ids",
        "theme_labels",
        "time_facets",
        "is_current",
    ),
}


def required_columns(table_name: str) -> tuple[str, ...]:
    return TABLE_CONTRACTS[table_name]
